[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

# Desative o plugin Next.js do Netlify se estiver causando problemas
# [plugins]
#   package = "@netlify/plugin-nextjs"
#   [plugins.inputs]
#     enableNextJs = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"